#!/bin/sh

case "$1" in
	remove|purge)
		# Remove the existing rules from sudoers file.
		sed "/NC10/d" /etc/sudoers > /etc/sudoers.new
		rm -f /etc/sudoers
		mv /etc/sudoers.new /etc/sudoers
		# Make sure that permissions and owner/group for sudoers file are good
		chown root:root /etc/sudoers
		chmod 440 /etc/sudoers

		# Remove status files
		rm -f /usr/lib/nc10/status/bluetooth
		rm -f /usr/lib/nc10/status/webcam
		rm -f /usr/lib/nc10/status/wireless

		# Update gconf default keybindings
		if [ -x /usr/bin/update-gconf-defaults ]; then
			update-gconf-defaults
		fi
		;;
esac
