#!/bin/sh

case "$1" in
	configure)
		# Remove old rules from sudoers file
		sed "/NC10/d" /etc/sudoers > /etc/sudoers.new
		rm -f /etc/sudoers
		mv /etc/sudoers.new /etc/sudoers
		# Make sure that permissions and owner/group for sudoers file are good
		chown root:root /etc/sudoers
		chmod 440 /etc/sudoers

		# Add new rules for the scripts that need them.
		echo "## Rule for NC10 scripts" >> /etc/sudoers
		echo "Cmnd_Alias	NC10_SCRIPT=/usr/bin/nc10" >> /etc/sudoers
		echo "%admin ALL=(ALL) NOPASSWD: NC10_SCRIPT" >> /etc/sudoers

		# Add status control files
		BLUETOOTH_STATUS="/usr/lib/nc10/status/bluetooth"
		WEBCAM_STATUS="/usr/lib/nc10/status/webcam"
		WIRELESS_STATUS="/usr/lib/nc10/status/wireless"
		if [ ! -f $BLUETOOTH_STATUS ]; then
			echo -n 1 > $BLUETOOTH_STATUS
		fi
		if [ ! -f $WEBCAM_STATUS ]; then
			echo -n 1 > $WEBCAM_STATUS
		fi
		if [ ! -f $WIRELESS_STATUS ]; then
			echo -n 1 > $WIRELESS_STATUS
		fi			

		# Update gconf default keybindings
		if [ -x /usr/bin/update-gconf-defaults ]; then
			update-gconf-defaults
		fi
		;;
esac
