#!/bin/bash

case ${1} in
	resume|thaw)
		if [ -f /etc/default/nc10-scripts ]; then
			. /etc/default/nc10-scripts
		else
			# Do nothing
			exit 0
		fi
		
		if [ $LAST_STATUS_RESTORE = "false" ]; then
			# We don't want to restore last status
			exit 0
		fi
		
		## Restore status of devices
		# Get last status
		BTS=`cat $BLUETOOTH_STATUS`
		WCS=`cat $WEBCAM_STATUS`
		WLS=`cat $WIRELESS_STATUS`
		
		# It's probably better to enable all devices, and
		# then disable the ones that should be disabled.
		nc10 bluetooth on
		nc10 webcam on
		nc10 wifi on
		sleep 2 # Wait some time, just in case

		if [ $BTS -eq 0 ]; then
			nc10 bluetooth off
		fi
		if [ $WCS -eq 0 ]; then
			nc10 webcam off
		fi
		if [ $WLS -eq 0 ]; then
			nc10 wifi off
		fi
		;;
esac

exit 0
