#!/bin/bash

case ${1} in
	resume|thaw)
		if [ -f /etc/default/samsung-scripts ]; then
			. /etc/default/samsung-scripts
		else
			# Do nothing
			exit 0
		fi

		if [ $LAST_STATUS_RESTORE = "false" ]; then
			# We don't want to restore last status
			exit 0
		fi

		## Restore status of devices
		# Get last status
		BTS=`cat $BLUETOOTH_STATUS`
		WCS=`cat $WEBCAM_STATUS`
		WLS=`cat $WIRELESS_STATUS`

		# It's probably better to enable all devices, and
		# then disable the ones that should be disabled.
		samsung-scripts bluetooth on
		samsung-scripts webcam on
		samsung-scripts wifi on
		sleep 3 # Wait some time, just in case

		if [ $BTS -eq 0 ]; then
			samsung-scripts bluetooth off
		fi
		if [ $WCS -eq 0 ]; then
			samsung-scripts webcam off
		fi
		if [ $WLS -eq 0 ]; then
			samsung-scripts wifi off
		fi
		;;
esac

exit 0
